// Generated by CoffeeScript 2.5.1
(function() {
  var pagseguro, req, xml;

  xml = require('jstoxml');

  req = require('request');

  pagseguro = class pagseguro {
    constructor(configObj) {
      if (arguments.length > 1) {
        this.email = arguments[0];
        this.token = arguments[1];
        this.mode = "payment";
        console.warn("This constructor is deprecated. Please use a single object with the config options as attributes");
      } else {
        this.email = configObj.email;
        this.token = configObj.token;
        this.mode = configObj.mode || "payment";
      }
      this.obj = {};
      this.xml = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>';
      return this;
    }

    currency(cur) {
      this.obj.currency = cur;
      return this;
    }

    reference(ref) {
      this.obj.reference = ref;
      return this;
    }

    addItem(item) {
      if (this.mode === 'subscription') {
        throw new Error("This function is for payment mode only!");
      }
      if (this.obj.items == null) {
        this.obj.items = [];
      }
      this.obj.items.push({
        item: item
      });
      return this;
    }

    buyer(buyer) {
      this.obj.sender = {
        name: buyer.name,
        email: buyer.email,
        phone: {
          areaCode: buyer.phoneAreaCode,
          number: buyer.phoneNumber
        }
      };
      if (this.mode === 'subscription') {
        this.obj.sender.address = {};
        if (buyer.street != null) {
          this.obj.sender.address.street = buyer.street;
        }
        if (buyer.number != null) {
          this.obj.sender.address.number = buyer.number;
        }
        if (buyer.postalCode != null) {
          this.obj.sender.address.postalCode = buyer.postalCode;
        }
        if (buyer.city != null) {
          this.obj.sender.address.city = buyer.city;
        }
        if (buyer.state != null) {
          this.obj.sender.address.state = buyer.state;
        }
        if (buyer.country != null) {
          this.obj.sender.address.country = buyer.country;
        }
        if (buyer.complement != null) {
          this.obj.sender.address.complement = buyer.complement;
        }
        if (buyer.district != null) {
          this.obj.sender.address.district = buyer.district;
        }
      }
      return this;
    }

    shipping(shippingInfo) {
      switch (this.mode) {
        case 'payment':
        case 'sandbox':
          this.obj.shipping = {
            type: shippingInfo.type,
            address: {
              street: shippingInfo.street,
              number: shippingInfo.number,
              postalCode: shippingInfo.postalCode,
              city: shippingInfo.city,
              state: shippingInfo.state,
              country: shippingInfo.country
            }
          };
          if (shippingInfo.complement != null) {
            this.obj.shipping.complement = shippingInfo.complement;
          }
          if (shippingInfo.district != null) {
            this.obj.shipping.district = shippingInfo.district;
          }
          break;
        case 'subscription':
          if (this.obj.sender == null) {
            this.obj.sender = {};
          }
          this.obj.sender.address = {
            street: shippingInfo.street,
            number: shippingInfo.number,
            postalCode: shippingInfo.postalCode,
            city: shippingInfo.city,
            state: shippingInfo.state,
            country: shippingInfo.country
          };
          if (shippingInfo.complement != null) {
            this.obj.sender.address.complement = shippingInfo.complement;
          }
          if (shippingInfo.district != null) {
            this.obj.sender.address.district = shippingInfo.district;
          }
      }
      return this;
    }

    // Configura custo do frete
    setShippingCost(cost) {
      switch (this.mode) {
        case 'payment':
        case 'sandbox':
        case 'subscription':
          this.obj.shipping = {
            cost: cost
          };
      }
      return this;
    }

    // Configura obrigatoriedade do endereço de entrega
    setAddressRequired(addressRequired) {
      switch (this.mode) {
        case 'payment':
        case 'sandbox':
        case 'subscription':
          this.obj.shipping = {
            addressRequired: addressRequired
          };
      }
      return this;
    }

    // Termos da assinatura
    preApproval(preApprovalInfo) {
      var maxTotalAmount, twoYearsFromNow;
      if (this.mode === 'subscription') {
        twoYearsFromNow = new Date();
        twoYearsFromNow.setFullYear(twoYearsFromNow.getFullYear() + 2);
        maxTotalAmount = preApprovalInfo.maxTotalAmount * 1 || preApprovalInfo.amountPerPayment * 24 || preApprovalInfo.maxAmountPerPayment * 24;
        this.obj.preApproval = {
          charge: preApprovalInfo.charge || 'manual', //'auto' or 'manual'
          finalDate: preApprovalInfo.finalDate || twoYearsFromNow.toJSON(), // Max 2 anos
          maxTotalAmount: maxTotalAmount.toFixed(2)
        };
        if (preApprovalInfo.name != null) {
          this.obj.preApproval.name = preApprovalInfo.name;
        }
        if (preApprovalInfo.details != null) {
          this.obj.preApproval.details = preApprovalInfo.details;
        }
        if (preApprovalInfo.period != null) {
          this.obj.preApproval.period = preApprovalInfo.period;
        }
        if (preApprovalInfo.amountPerPayment != null) {
          this.obj.preApproval.amountPerPayment = preApprovalInfo.amountPerPayment;
        }
        if (preApprovalInfo.maxAmountPerPayment != null) {
          this.obj.preApproval.maxAmountPerPayment = preApprovalInfo.maxAmountPerPayment;
        }
        if (preApprovalInfo.maxPaymentsPerPeriod != null) {
          this.obj.preApproval.maxPaymentsPerPeriod = preApprovalInfo.maxPaymentsPerPeriod;
        }
        if (preApprovalInfo.maxAmountPerPeriod != null) {
          this.obj.preApproval.maxAmountPerPeriod = preApprovalInfo.maxAmountPerPeriod;
        }
        if (preApprovalInfo.initialDate != null) {
          this.obj.preApproval.initialDate = preApprovalInfo.initialDate;
        }
      } else {
        throw new Error("This function is for subscription mode only!");
      }
      return this;
    }

    /*
    Configura as URLs de retorno e de notificação por pagamento
    */
    setRedirectURL(url) {
      this.obj.redirectURL = url;
      return this;
    }

    setNotificationURL(url) {
      this.obj.notificationURL = url;
      return this;
    }

    // Configura URL de revisão dos termos de assinatura
    setReviewURL(url) {
      if (this.mode === "subscription") {
        this.obj.reviewURL = url;
      } else {
        throw new Error("This function is for subscription mode only!");
      }
      return this;
    }

    send(callback) {
      var options;
      options = {
        method: 'POST',
        headers: {
          'Content-Type': 'application/xml; charset=UTF-8'
        }
      };
      switch (this.mode) {
        case 'payment':
          options.uri = `https://ws.pagseguro.uol.com.br/v2/checkout?email=${this.email}&token=${this.token}`;
          options.body = this.xml + xml.toXML({
            checkout: this.obj
          });
          break;
        case 'subscription':
          options.uri = `https://ws.pagseguro.uol.com.br/v2/pre-approvals/request?email=${this.email}&token=${this.token}`;
          options.body = this.xml + xml.toXML({
            preApprovalRequest: this.obj
          });
          break;
        case 'sandbox':
          options.uri = `https://ws.sandbox.pagseguro.uol.com.br/v2/checkout?email=${this.email}&token=${this.token}`;
          options.body = this.xml + xml.toXML({
            checkout: this.obj
          });
      }
      return req(options, function(err, res, body) {
        if (err) {
          return callback(err);
        } else {
          return callback(null, body);
        }
      });
    }

  };

  module.exports = pagseguro;

}).call(this);
